// WordPress webpack config.
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

// Plugins.
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );
const BrowserSyncPlugin = require('browser-sync-webpack-plugin');

// Utilities.
const path = require( 'path' );

// Add any new entry points by extending the webpack config.
module.exports = {
	...defaultConfig,
	...{
		entry: {
			'js/theme':  path.resolve( process.cwd(), 'src/js',   'main.js'   ),
			'css/theme': path.resolve( process.cwd(), 'src/scss', 'main.scss' ),
		},
		plugins: [
			// Include WP's plugin config.
			...defaultConfig.plugins,

            

			// Removes the empty `.js` files generated by webpack but
			// sets it after WP has generated its `*.asset.php` file.
			new RemoveEmptyScriptsPlugin( {
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
			} ),

            // BrowserSync for live reload across devices
            new BrowserSyncPlugin(
                {
                    proxy: 'https://top-trend.ddev.site', // Your DDEV site URL
                    files: [
                        '**/*.php',
                        'src/**/*.js',
                        'src/**/*.scss'
                    ],
                    open: false,
                    https: {
                        key: path.resolve(process.cwd(), '.ddev/traefik/certs/top-trend.key'),
                        cert: path.resolve(process.cwd(), '.ddev/traefik/certs/top-trend.crt'),
                    },
                    https: true,
                    reloadDelay: 0,
                },
                {
                    reload: false // Let webpack handle reload
                }
            ),
		],
	}
};